### ISSUE TITLE
How to install and run wgdi

### ISSUE THREAD

**Issue by sajjadasaf** [SunPengChuan/wgdi#1]
I am new to python.
Please guide me how to install and run this software.
I tried but end with following error

sajjad@sajjad-ThinkStation-P910:~/Downloads/wgdi-master$ pip install wgdi
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Defaulting to user installation because normal site-packages is not writeable
Collecting wgdi
  Using cached WGDI-0.1.6.tar.gz (10 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-7IAocz/wgdi/setup.py'"'"'; __file__='"'"'/tmp/pip-install-7IAocz/wgdi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-8CE1wk
         cwd: /tmp/pip-install-7IAocz/wgdi/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-7IAocz/wgdi/setup.py", line 6, in <module>
        with open("README.md", "r",encoding='utf-8') as fh:
    TypeError: 'encoding' is an invalid keyword argument for this function
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by SunPengChuan** [comment]
wgdi support for Python 3
