### ISSUE TITLE
ERROR: inconsistency between the following pep and nuc seqs

### ISSUE THREAD

**Issue by xuzhougeng** [SunPengChuan/wgdi#12]
when I run the `wgdi ks`  , i met the following error

```
#---  ERROR: inconsistency between the following pep and nuc seqs  ---#
>gene_name
cds seq
>gene_name
pep seq

which: no bl2seq in (xxx)
Run bl2seq (-p tblastn) or GeneWise to see the inconsistency.
```

When search the bl2seq, I found the bl2seq was only in legacy blast (see <https://www.biostars.org/p/17580/>

Could I ignore this error, or how could I solve the problem.

**Comment by SunPengChuan** [comment]
In most cases, it is a sequence alignment problem. I think it is necessary to check it. Once you know the reason, you can ignore it.

**Comment by SunPengChuan** [comment]
This error occurs when there is a stop-codon （such as *） in the sequence.

**Comment by YZW0118** [comment]
Excause me, have you solved your problem? I met the same problem recently.

**Comment by fatelitier** [comment]
> 请问我，你的问题解决了吗？我最近遇到了同样的问题。

I had the same problem. Did you solve it? Could you share some ideas?

**Comment by fatelitier** [comment]
> Excause me, have you solved your problem? I met the same problem recently.

I had the same problem. Did you solve it? Could you share some ideas?

**Comment by SunPengChuan** [comment]
The ks value is blank for the gene pair triggering the warning. If not widespread, no need to pay much attention.
