### ISSUE TITLE
ksfigure becomes color-filled blocks instead of lines

### ISSUE THREAD

**Issue by tinyhys** [SunPengChuan/wgdi#13]
Dear developers, thanks to your excellent software!
I have tried the wgdi -kf command using the example ks_fit_result.csv, however I got a ks figure with  color-filled blocks instead of lines. Could you please tell me how can I change them to lines? Many thanks!

![kf](https://user-images.githubusercontent.com/37066354/129848019-997726f3-df1c-4645-a386-cb22e16e4eee.png)

**Comment by SunPengChuan** [comment]
![image](https://user-images.githubusercontent.com/13791541/129855211-79b9faa7-3e47-489d-8351-0de3fd1f8c92.png)
Uncomment the area, and comment out the following two lines, like this.
![image](https://user-images.githubusercontent.com/13791541/129855730-a84966cb-4b05-4017-9e9e-2856933e1468.png)

**Comment by tinyhys** [comment]
> ![image](https://user-images.githubusercontent.com/13791541/129855211-79b9faa7-3e47-489d-8351-0de3fd1f8c92.png)
> Uncomment the area, and comment out the following two lines, like this.
> ![image](https://user-images.githubusercontent.com/13791541/129855730-a84966cb-4b05-4017-9e9e-2856933e1468.png)

thanks to your timely reply! I will learn more about this great tool~
