### ISSUE TITLE
separate Gaussian Fitting for two or more peaks 

### ISSUE THREAD

**Issue by tinyhys** [SunPengChuan/wgdi#14]
Dear teacher,
    After acquiring the correspondence block output file _c.csv_ using **-c** module and then running the **kspeaks** module, I got the _kp.png_ which showed two peaks. 
    I would like to **peaksfit** a Ks density distribution which contained two peaks. So I tried to separate the **area**  in peaksfit.conf to 0,1.2 and 1.2,2.5  to run the **peaksfit** module and I did obtain two sets of Gaussian Fitting parameter. However, these parameter seemed not to share a common Frequency (axis Y) scale comparing to the _kp.png_.
    How can I get multiple sets of  Gaussian Fitting parameter which could share same layout in the kp.png? 
    By the way, this is an inter-species ks distribution, I do not really understand what the two peaks mean respectively. I think the peak in ks≈0.1 represents the divergence event of these two species, am I right or not? And I have no idea about the first peak.
MANY THANKS !
![kp](https://user-images.githubusercontent.com/37066354/133380961-a793ef78-8b53-4bcb-9623-2472cc668b07.png)

**Comment by SunPengChuan** [comment]
There are related discussions in the comments section below this video. https://www.bilibili.com/video/BV195411P7L1/ .

**Comment by tinyhys** [comment]
Thanks a lot !

**Comment by SunPengChuan** [comment]
In my opinion, the blocks generated by different events can be distinguished. Therefore, you can simply filter the blocks generated by an event based on homo, ks, and even delete inappropriate blocks by modifying the blockinfo.csv file. You can judge whether your processing is appropriate through the -bk parameter.

**Comment by SunPengChuan** [comment]
For ks peaks between different species, the first peak may be related to the divergence. Sometimes the recent polyploid events overlap with the divergence and merge into one. The ancient Ks peak should be related to the shared polyploid event.

**Comment by tinyhys** [comment]
> For ks peaks between different species, the first peak may be related to the divergence. Sometimes the recent polyploid events overlap with the divergence and merge into one. The ancient Ks peak should be related to the shared polyploid event.

I reviewed some related papers and tried to understand that the ks≈1.8 peak was the WGD event happened their common ancestry and the ks≈0.1 peak was the divergence peak, which means the same as you said.

That helps a lot , best regards !
