### ISSUE TITLE
sep="\n" cause ValueError?

### ISSUE THREAD

**Issue by ElkanChang** [SunPengChuan/wgdi#16]
Hi Pengchuan,

Thanks for your great work!

I had trouble when running WGDI. Pandas raise ValueError as follows:

```
--skip--
File "/home/testchamber/anaconda3/envs/wgdi/lib/python3.10/site-packages/wgdi/ks.py", line 33, in auto_file
    p = pd.read_csv(self.pairs_file, sep='\n', header=None, nrows=30)
--skip--
File "/home/testchamber/anaconda3/envs/wgdi/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1533, in _refine_defaults_read
    raise ValueError(
ValueError: Specified \n as separator or delimiter. This forces the python engine which does not accept a line terminator. Hence it is not allowed to use the line terminator as separator.
```

Could you kindly give me some suggestions?

**Comment by SunPengChuan** [comment]
Can you upload the pairs_file file?

**Comment by SunPengChuan** [comment]
Someone has a similar problem, his python version is 3.10. Is the same for your python version?

**Comment by ElkanChang** [comment]
> Someone has a similar problem, his python version is 3.10. Is the same for your python version?

Yes, that's true, we have the same problem. I also replied in the issue he opened, thanks!

**Comment by ElkanChang** [comment]
Add reference issue #17

**Comment by longrc** [comment]
> Someone has a similar problem, his python version is 3.10. Is the same for your python version?

I also had the same problem after installing new version of wgdi recently. I find this problem is caused by new version of Pandas (>=1.4.0), not by Python. If you install wgdi by conda, new version of Pandas=1.4.1 will installed automatically. Downgrade Pandas to 1.3.5 will solve this problem.
