### ISSUE TITLE
wgdi -kf legend

### ISSUE THREAD

**Issue by pxxiao-hz** [SunPengChuan/wgdi#18]
Hello,

I using `wgdi -kf all.conf` to plot ks figure, ksfit file from `wgdi -kf ?`, but I found the figure legend has some promblem.
![image](https://user-images.githubusercontent.com/76642822/158043985-e92f82bd-51fc-435d-9228-87d971b6964e.png)
I don't know if it's my fault or bug. 

wgdi was installed through conda, and python version was 3.8.6 or 3.9.7.

Thanks.
Best wishes!

**Comment by SunPengChuan** [comment]
It is, indeed, a bug. I fixed it and am now ready to update it.

**Comment by pxxiao-hz** [comment]
Thanks for your reply.

I tried Grape and Acoerulea and found not the same as what you did. Is there a problem with this result? The picture is shown below.
![image](https://user-images.githubusercontent.com/76642822/158060086-61df493f-ac29-404f-91cf-07d56206d6ad.png)
There are only 408 Alignments for grapes and 226 for Acoerulea. I remember that the grape you did more than 1000 alignments. Does scaffold need to be included in the process of calculation?

In addition, is there a user group of wgdi, such as QQ group?

Thanks again.
Best wishes！

**Comment by SunPengChuan** [comment]
Scaffold, in general, does not need to be considered, only the extracted blocks. You can also add QQ: 966612552.
