### ISSUE TITLE
Wgd events of multi-genomes

### ISSUE THREAD

**Issue by ardy20** [SunPengChuan/wgdi#23]
Hello
I am trying to use this tool. I was wondering to use it for the WGD of 3 or more different genomes and combine the graph of multiple genomes in one figure file?

**Comment by SunPengChuan** [comment]
Multiple ks peaks of different genomes are shown in one Figure, you should use the ’-kf‘ parameter of WGDI.

**Comment by ardy20** [comment]
Thanks. Could you please give an example command?

**Comment by SunPengChuan** [comment]
You can first use `wgdi -kf example >total.conf`, then, there will be a file `ks_fit_result.csv` in the current directory, revise the species of Ks peaks, and execute the command `wgdi -kf total.conf`.

**Comment by ardy20** [comment]
Ok. What the example would be? genome.cds.fasta

**Comment by SunPengChuan** [comment]
The example is at https://github.com/SunPengChuan/wgdi-example/tree/main/dotplot/all.conf.  Demo video at https://www.bilibili.com/video/BV1qK4y1U7eK  and https://www.bilibili.com/video/BV195411P7L1.

**Comment by ardy20** [comment]
Thanks Sunpeng I am going to try it soon. Unfortunately the videos cannot be played in higher quality as it needs bilibili account which I couldn't create from Australia. Unfortunately I don't know chinese language.
Is there any guide on how to prepare input files such as gff and lens files?  Could the videos be uploaded on YouTube.
Regards
Ardy

**Comment by SunPengChuan** [comment]
I will upload a copy to youtube soon

**Comment by ardy20** [comment]
Ok Thanks. If you share it with me I can do it on your behalf.

**Comment by SunPengChuan** [comment]
email ？

**Comment by ardy20** [comment]
Google Drive and then send the link to me, if possible.

**Comment by SunPengChuan** [comment]
https://drive.google.com/drive/folders/1zUSVD1rotLa9tBG-hXc3P5Mpr7d4ViB9?usp=share_link

**Comment by ardy20** [comment]
Thanks SunPeng
I need your consent to upload on Youtube.

**Comment by SunPengChuan** [comment]
You can upload it, and it's even better if you add the English dub.

**Comment by ardy20** [comment]
Here are the You tube links:

Part 1:
https://youtu.be/k-S6FVcBIQw

Part 2:
https://youtu.be/QiZYFYGclyE

**Comment by erika-r-moore** [comment]
> Here are the You tube links:
> 
> Part 1: https://youtu.be/k-S6FVcBIQw
> 
> Part 2: https://youtu.be/QiZYFYGclyE

Is it possible to get CC on these videos? I am hoping to auto-translate the video to English, but most solutions require CC first!

**Comment by SunPengChuan** [comment]
Yes, you can do that. I hope you can also add links to some examples, such as [Karyotype evolution](https://github.com/SunPengChuan/wgdi-example/blob/main/Karyotype_Evolution.md) and [phase subgenomes](https://github.com/SunPengChuan/wgdi-example/blob/main/phase_subgenomes.md).

**Comment by erika-r-moore** [comment]
Hello! I have added English subtitles to the YouTube videos. Please note that the subtitles were generated using AI, so they may be incomplete or inaccurate.

Here are the YouTube links with English subtitles:
Part 1: https://youtu.be/5Y_YszXcTsE
Part 2: https://youtu.be/7jIgFyP1Vvk
