### ISSUE TITLE
ks result is empty 

### ISSUE THREAD

**Issue by ardy20** [SunPengChuan/wgdi#27]
Hello
I prepared the total.conf as follows but the result is empty. Could you please guide?

[ks]
cds_file = /scratch/project_mnt/S0030/wgdi/male-female/male.cds.fa
pep_file = /scratch/project_mnt/S0030/wgdi/male-female/male.pep.fa
align software = muscle
pairs_file = /scratch/project_mnt/S0030/wgdi/male-female/collinearity_file
ks_file = ks_result

the collinerarity file is from Improved collinearity step.

Also how to prepare files for two species?

**Comment by ardy20** [comment]
Header of collinearity file:

![collinearity_file](https://user-images.githubusercontent.com/63028911/209813481-e09b8fe8-78d3-40e9-a72e-819048555776.JPG)

**Comment by SunPengChuan** [comment]
If two or more different species, cat them to one file.
If the ks result is empty, delete it and run again.

**Comment by ardy20** [comment]
I run the Ks analysis several times but it is still empty. It only shows one line of Wgdi -ks analysis (its header). My conda environment uses python 11. Could this be a conda python issue?

**Comment by SunPengChuan** [comment]
Delete the file named 'pep' in this directory

**Comment by ardy20** [comment]
Hi
I think I found the error. In ks documentation, in total.config file there is a missing underline, in which align software should be converted to align_software

I mean: align software > align_software
