### ISSUE TITLE
wgdi -icl error

### ISSUE THREAD

**Issue by cfz1998** [SunPengChuan/wgdi#29]
Hi!@SunPengChuan
When i use `wgdi -icl  *_collinearity.conf` to find collinearity genes in one genome. I got an error!
![image](https://user-images.githubusercontent.com/60096719/226176605-5301c01a-8ad6-410c-97b0-286c4287e7d7.png)

I don't know why.
Thank you for your reply!

**Comment by cfz1998** [comment]
sample1_collinearity.conf
```
gff1 =  sample1.gff
gff2 =  sample1.gff
lens1 = sample1.len
lens2 = sample1.len
blast = ../02.mcscanx/sample1.blast
blast_reverse = false
multiple  = 1
process = 8
evalue = 1e-5
score = 100
grading = 50,40,25
mg = 25,25
pvalue = 1
repeat_number = 10
positon = order
savefile = sample1.coll
```

**Comment by SunPengChuan** [comment]
It looks like a problem with pandas. Could you please upload your data so I can test it? Alternatively, you can send it to me separately via email : sunpengchuan@gmail.com

**Comment by cfz1998** [comment]
[Actinidia_chinensis.tar.gz](https://github.com/SunPengChuan/wgdi/files/11013248/Actinidia_chinensis.tar.gz)

**Comment by SunPengChuan** [comment]
The GFF file you are processing has issues. Such as
Lachesis_group13	Actinidia07289.t1	6088347	6108665	-	489
Lachesis_group13	Actinidia07290.t1	6088770	6091853	-	489

I'll send you the processed GFF file and the script to process it.
[Actinidia_chinensis.zip](https://github.com/SunPengChuan/wgdi/files/11015984/Actinidia_chinensis.zip)

**Comment by cfz1998** [comment]
> 

There is something wrong with `from collections import defaultdict`. Thanks!
