### ISSUE TITLE
No "-bi" result file generation

### ISSUE THREAD

**Issue by Wenwen012345** [SunPengChuan/wgdi#38]
Hello. @SunPengChuan 

Just for this one comparison, I ran the comparison for both species but the result file generated with the "-bi" parameter is empty. I carefully checked the .conf file but no problem was found. The comparison of the two species by themselves and the comparison of the two species with any other species produces the results normally. So I don't really understand what is causing this. Can you take a look for me?

[Ro_cac.conf_et_al.zip](https://github.com/SunPengChuan/wgdi/files/12136776/Ro_cac.conf_et_al.zip)
[Ro_cac.cds.zip](https://github.com/SunPengChuan/wgdi/files/12136788/Ro_cac.cds.zip)
[Ro_cac.pep.zip](https://github.com/SunPengChuan/wgdi/files/12136789/Ro_cac.pep.zip)

**Comment by SunPengChuan** [comment]
It would be great if the order of species comparison was the same in all the files. Note that it is not the file names, but the content that needs to be consistent.
[blockinfo]
blast = Ro_cac.blast
blast_reverse = true
gff2 =  Ro.gff
gff1 =  Cac.gff
lens2 = Ro.len
lens1 =  Cac.len
collinearity = Ro_cac.collinearity
score = 100
evalue = 1e-5
repeat_number = 20
position = order
ks = Ro_cac.ks
ks_col = ks_NG86
savefile = Ro_cac.block.information.csv

**Comment by Wenwen012345** [comment]
> 

I tried, it doesn't work. The problem should be something else.

**Comment by Wenwen012345** [comment]
> It would be great if the order of species comparison was the same in all the files. Note that it is not the file names, but the 
I tried, it doesn't work. The problem should be something else.

**Comment by SunPengChuan** [comment]
[Ro_cac.zip](https://github.com/SunPengChuan/wgdi/files/12136909/Ro_cac.zip)

**Comment by Wenwen012345** [comment]
> [Ro_cac.zip](https://github.com/SunPengChuan/wgdi/files/12136909/Ro_cac.zip)

Okay. Thank you! Parameter adjustment is an eye test. I seem to have missed an adjustment in the right place earlier; and I was a bit dizzy from some wine yesterday. The following error occurred yesterday:
`ValueError: need at least one array to concatenate`

Anyway, thank you very much!
