### ISSUE TITLE
Legend error for "-kf" results

### ISSUE THREAD

**Issue by Wenwen012345** [SunPengChuan/wgdi#39]
Hello! @SunPengChuan 

I have encountered a bug in the legend of the "-kf" results, could you suggest a solution? And could you suggest a way to change the fill colour of the lines to white?

![image](https://github.com/SunPengChuan/wgdi/assets/63379795/74d053d9-1341-4dbc-861a-1183714127ea)

all.kf.conf
```
[ksfigure]
ksfit = ks_fit_result.csv
labelfontsize = 15
legendfontsize = 15
xlabel = none
ylabel = none
title = none
area = 0,4
figsize = 10,6.18
savefig =  all_ks.svg
```
[ks_fit_result.csv](https://github.com/SunPengChuan/wgdi/files/12138365/ks_fit_result.csv)

**Comment by SunPengChuan** [comment]
You can add shadow = false to the parameters.

**Comment by Wenwen012345** [comment]
Okay! It just worked!
