### ISSUE TITLE
Error in creating dotplot, ValueError: cannot reindex on an axis with duplicate labels

### ISSUE THREAD

**Issue by salmanento** [SunPengChuan/wgdi#41]
I am trying to create dotplot using two genomes for whole genome duplication detection. I am facing issue (ValueError: cannot reindex on an axis with duplicate labels) screenshot of error attached. I have also attached the Screenshot of GFF1, GFF2, Lens1 & Lens2 & Blast files used. Please look into it and guide about the issue and make me able to proceed with the analysis.

Below is the total.conf script
[dotplot]
blast = /home/lilin/wgd-exp/dotplot/updated/blastp_output.blast
gff1 =/home/lilin/wgd-exp/dotplot/updated/X.ripnewide_gene.gff
gff2 = /home/lilin/wgd-exp/dotplot/updated/S. gregaria_updatedgene.gff
lens1 = /home/lilin/wgd-exp/dotplot/updated/lens1_X.riparia.lens
lens2 =/home/lilin/wgd-exp/dotplot/updated/lens2_S.gregaria.lens
genome1_name =  Xya_riparia
genome2_name =  Schistocerca_gregaria
multiple  = 1
score = 100
evalue = 1e-5
repeat_number = 10
position = order
blast_reverse = false
ancestor_left = none
ancestor_top = none
markersize = 0.5
figsize = 10,10
savefig = /home/lilin/wgd-exp/dotplot/updated/dotplot.png

Attachments
![Error](https://github.com/SunPengChuan/wgdi/assets/147240366/1099b316-d598-486b-84cf-a4a063e3a8af)
![GFF1](https://github.com/SunPengChuan/wgdi/assets/147240366/46466996-de93-4509-93ae-a03c97d0c6df)
![GFF2](https://github.com/SunPengChuan/wgdi/assets/147240366/9ab16ba7-39f9-4fd4-b5df-473f80cf801d)
![lens1](https://github.com/SunPengChuan/wgdi/assets/147240366/a5be4ed6-05a8-4f28-ab20-4a30235d6cdd)
![lens2](https://github.com/SunPengChuan/wgdi/assets/147240366/bcd68c6b-b6fe-4d74-9bdb-b775d8e3725c)
![BlAST](https://github.com/SunPengChuan/wgdi/assets/147240366/4a1866de-7a48-4ecb-a911-65ac18c14425)

**Comment by SunPengChuan** [comment]
There seems to be a problem when handling gff files, specifically regarding the alignment between the initial two columns in the blast file and the second column within the gff file.

**Comment by salmanento** [comment]
Thank you, resolved. Dotplot created, Please check it is Ok?
Can you please help me how to interpret the dotplot results?

![savefile](https://github.com/SunPengChuan/wgdi/assets/147240366/4aa03b10-9d10-422b-8b4d-152c37d9fb74)

**Comment by SunPengChuan** [comment]
Your results show no significant collinearity between the two species. Could their divergence be too great? Consider using closer species to check if it’s a data processing issue.

**Comment by SunPengChuan** [comment]
The reason why the second figure doesn’t have clear synteny blocks is leading to incorrect results in your subsequent analysis.

**Comment by salmanento** [comment]
Now, I have used two closely related species, belonging from same genus. Look into the results please.

![dotplot](https://github.com/SunPengChuan/wgdi/assets/147240366/ce479ea8-22cc-4b03-aa77-8fc92dcb8bb2)
![blockKs](https://github.com/SunPengChuan/wgdi/assets/147240366/785cd79c-83a8-4fd5-a19d-3385d92e940c)
![kspeaks](https://github.com/SunPengChuan/wgdi/assets/147240366/3c3fa21f-b2c2-45c5-80a5-f674b03b7811)
![peaksfit](https://github.com/SunPengChuan/wgdi/assets/147240366/9a9b1fff-053d-452b-8be0-3ae14488919f)
![Ksfigure](https://github.com/SunPengChuan/wgdi/assets/147240366/e8ac80c6-37d0-481a-b576-a8ff36294b54)
![align](https://github.com/SunPengChuan/wgdi/assets/147240366/349f6129-dc87-440e-add7-e4d3714fb1ac)
