### ISSUE TITLE
Why polyploidy classification without a underline (_)

### ISSUE THREAD

**Issue by xiekunwhy** [SunPengChuan/wgdi#42]
Hi,

All parameters name with a underline (_) to connect spaces except \[polyploidy classification\], why?

\[polyploidy classification\]
blockinfo = block information (*.csv)
ancestor_left = ancestor file
ancestor_top = ancestor file
classid = class1,class2
savefile = result file(.csv)

Best,
Kun

**Comment by SunPengChuan** [comment]
It has no special meaning.
