### ISSUE TITLE
PeaksFit do not show two peaks

### ISSUE THREAD

**Issue by amvarani** [SunPengChuan/wgdi#44]
Hi there,
I have the following pattern showing two peaks.

![image](https://github.com/SunPengChuan/wgdi/assets/3044067/afd1bed3-a9d9-4810-9a88-e7762dc5fa7a)

However, when I try to plot the PeaksFit, I have got this:

![image](https://github.com/SunPengChuan/wgdi/assets/3044067/8c7aa5da-3735-4a67-b9f9-90ed1a97cabd)

How to get two (or more) sets of Gaussian curves?  

I was not able to follow the solution found in: https://github.com/SunPengChuan/wgdi/issues/14

**Comment by SunPengChuan** [comment]
The most precise approach involves using the -c parameter in WGDI to partition the synteny blocks for various events, subsequently acquiring the ks peaks. In your context, you can directly utilize the area parameter of the -pf subroutine in WGDI. You can set it to 0.1,0.5 and 1,2 respectively to capture two peak values in two separate instances.

**Comment by amvarani** [comment]
Hi there!
Thanks, but what I can do when I got weird things like that ? 
![image](https://github.com/SunPengChuan/wgdi/assets/3044067/a7693617-bb54-4ecc-886c-e3ff54500c5f)

**Comment by SunPengChuan** [comment]
In this scenario, you should consider the results from both the -d and -bk options, and then filter the blocks accordingly. Modify the ‘homo’ and ‘multiple’ parameters in the C subroutine for more effective filtering.

**Comment by amvarani** [comment]
Ok! Perfect, I am addressing that now.
Another question: While reviewing our manuscript and documents, I noticed the tandem parameter. According to the manuscript, when enabled in kspeaks, the tandem parameter may reveal peaks not necessarily originating from WGD events, but from tandem duplications or other processes that generate non-syntenic paralogs. Is that correct?

The above image was generated with 'tandem=true' in kspeaks. In the image below, the tandem was set to false. Does this mean the first peak in the above image might not represent a WGD event?

![image](https://github.com/SunPengChuan/wgdi/assets/3044067/8c927f0e-e052-4aa1-b534-44c325466065)

**Comment by SunPengChuan** [comment]
you are right.
