### ISSUE TITLE
Karyotype Evolution

### ISSUE THREAD

**Issue by amvarani** [SunPengChuan/wgdi#45]
Dear @SunPengChuan , I  need your help again

I was following your documentation on: https://github.com/SunPengChuan/wgdi-example/blob/main/Karyotype_Evolution.md and trying to generate a paleogenomics analysis of my species, which is close to Populus-Salix. 

Following the example, I got it 
![image](https://github.com/SunPengChuan/wgdi/assets/3044067/3aad032c-bc18-4b7a-97a7-5b4763646a71)

After using -bk my results are:
![image](https://github.com/SunPengChuan/wgdi/assets/3044067/4978b0bf-0fd9-4317-bb08-7b6ce84e1a3e)

Finally, when I map using the -km to map AEK I got only seven chromossomes from the AEK, and have this:

![image](https://github.com/SunPengChuan/wgdi/assets/3044067/b8ad03bc-7fa0-4e65-9691-b9564777eb1e)

I would also like to plot the Karyotype style figure. Can you help me ?

**Comment by SunPengChuan** [comment]
The process of chromosomal evolution presented here deviates considerably from prior methodologies, moving beyond a mere straightforward mapping. The emphasis is placed on identifying both the shared and unique chromosomal structural variations across different species, providing a more nuanced understanding of genetic diversity.
