### ISSUE TITLE
error with -kf function in wgdi used to make ks figure

### ISSUE THREAD

**Issue by RezwanCAAS** [SunPengChuan/wgdi#46]
Hi, I am using WGDI and all steps were successfully completed but when tried to draw the ks figure using the following command 
wgdi -kf total.conf

a chunk of data is shared here
[ks_medain.csv](https://github.com/SunPengChuan/wgdi/files/13730223/ks_medain.csv)

 Moreover, I used the input data (ks_medain), output of speaks (-kp) 
 
 `[ksfigure]
ksfit = ks_medain
labelfontsize = 15
legendfontsize = 15
xlabel = none
ylabel = none
title = none
area = 0,2
figsize = 10,6.18
shadow = true
savefig = ksfigure`

here is the error 

`File "/home/tariqr/.local/bin/wgdi", line 33, in <module>
    sys.exit(load_entry_point('wgdi==0.6.5', 'console_scripts', 'wgdi')())
  File "/ibex/sw/rl9c/wgdi/0.6.3/rl9.1_conda3/Miniconda3/envs/python3.8/lib/python3.8/site-packages/wgdi/run.py", line 163, in main
    module_to_run(arg, value)
  File "/ibex/sw/rl9c/wgdi/0.6.3/rl9.1_conda3/Miniconda3/envs/python3.8/lib/python3.8/site-packages/wgdi/run.py", line 122, in module_to_run
    run_subprogram(program, conf, name)
  File "/ibex/sw/rl9c/wgdi/0.6.3/rl9.1_conda3/Miniconda3/envs/python3.8/lib/python3.8/site-packages/wgdi/run.py", line 87, in run_subprogram
    r.run()
  File "/ibex/sw/rl9c/wgdi/0.6.3/rl9.1_conda3/Miniconda3/envs/python3.8/lib/python3.8/site-packages/wgdi/ksfigure.py", line 50, in run
    ax.plot(t, self.Gaussian_distribution(
  File "/ibex/sw/rl9c/wgdi/0.6.3/rl9.1_conda3/Miniconda3/envs/python3.8/lib/python3.8/site-packages/wgdi/ksfigure.py", line 33, in Gaussian_distribution
    if np.isnan(k[3 * i + 2]):
IndexError: index 2 is out of bounds for axis 0 with size 0`

**Comment by SunPengChuan** [comment]
The -kf of WGDI is executed after -pf. It should be noted that the result of reading is the fitting curve function recorded by -pf, which needs to be recorded manually.

**Comment by RezwanCAAS** [comment]
Thank you. I got your first statement and I have made figure with -pf.

![peaksfit](https://github.com/SunPengChuan/wgdi/assets/42382456/a48323e1-d7a7-48b9-9e2a-da9e36899132)

but for the second statement about the "recorded manually", cannot understand this. Can you please elaborate to fix this issue for -kf.

**Comment by SunPengChuan** [comment]
At around 19:48 and 36 minutes in the video at https://www.youtube.com/watch?v=qzyfygcLYe, you can find the operating instructions.

**Comment by RezwanCAAS** [comment]
sorry Sun, the link does not work. It's a broken link. I have access to youtube and bili bili. if you have any of the other link, please share.

**Comment by SunPengChuan** [comment]
https://www.bilibili.com/video/BV195411P7L1/

**Comment by RezwanCAAS** [comment]
Great. it's done. Thank you so much Sun for your great help.


[save_image.pdf](https://github.com/SunPengChuan/wgdi/files/13743067/save_image.pdf)
