### ISSUE TITLE
The number of gene pairs in the KS result file is not equal to the number of gene pairs in collinearity file

### ISSUE THREAD

**Issue by cfz1998** [SunPengChuan/wgdi#49]
Hi.@SunPengChuan

My collinear file has 40,528 gene pairs. Why does the result Ks file have only 23,960 gene pairs?

```
[ks]
cds_file = all.cds.fa
#cat all cds files together
pep_file = all.pep.fa
#cat all pep files together
align_software = mafft
pairs_file = A_A.collinear
ks_file = A_A.ks
```

A_A.collinear: 40,528 gene pairs
A_A.ks: 23,960 gene pairs

**Comment by SunPengChuan** [comment]
Two genes (gene1 vs gene2) of the same species are equivalent to (gene2 vs gene1), thus eliminating numerous distinct combinations.

**Comment by cfz1998** [comment]
Thank you for your reply!
