### ISSUE TITLE
关于将现存物种映射到祖先物种并作ks图的问题

### ISSUE THREAD

**Issue by Sa-ku-mo** [SunPengChuan/wgdi#50]
孙老师好，
https://github.com/SunPengChuan/wgdi-example/blob/main/Karyotype_Evolution.md 的教程中提到，用_T. sinense_映射到AEK上，并依次使用-icl -bi -c -bk得到如下的ks图，#45 中也展示了类似的图片
![image](https://github.com/SunPengChuan/wgdi/assets/41478553/f2b1c8c8-8210-465f-89e7-fdf24e1c715c)
但-bi需要ks文件作为输入，而-ks分析需要物种的cds文件，组装得到的祖先只有蛋白质序列，请问这一步应当如何复现呢？

**Comment by SunPengChuan** [comment]
ks=none

**Comment by Sa-ku-mo** [comment]
感谢您的解答
